### ISSUE TITLE
ScrapMagnet down again for 2 days

### ISSUE THREAD

**Issue by robjg3** [sharkone/BitTorrent.bundle#119]
Yup..its down yet again.  Any idea on fix/update?

![image](https://user-images.githubusercontent.com/49775120/57661121-8b6aad80-75b7-11e9-9c43-22c4268a628f.png)

**Comment by sharkone** [comment]
Just restart your server.

**Comment by robjg3** [comment]
Yaa...i did and it finally came back up.  Thanks.  It keep happening all the time.  I just upgraded to the new version in hopes that is fixed.  Awesome job with plugin.  I use it regularly.
