### ISSUE TITLE
AppleTV Plexconnect Crashes While Playing Video

### ISSUE THREAD

**Issue by computersteve** [sharkone/BitTorrent.bundle#20]
AppleTV with Plexconnect and this plugin are very unstable. Most of the time the plugin either times out while loading a movie displaying an eventual error message stating that an error occurred loading this content. Now sometimes if you start the video over and over again sometimes it will eventually load but even if it does the plugin is unstable and minutes into video playback it eventually crashes the AppleTV causing the spinning circle resulting in you being brought back to the AppleTV Main Menu. Some info the Apple TV iOS Version is the latest 6.1 and Plex Media Server 0.9.9.7.429-f80a8d6 for OSX.

**Comment by sharkone** [comment]
Most likely resolved now
