### ISSUE TITLE
Fix Linux/x64

### ISSUE THREAD

**Issue by sharkone** [sharkone/BitTorrent.bundle#21]

**Comment by sgu222e** [comment]
I'm chiming in to follow this issue since I'm using Fedora x64.
Will continue to plug around myself and see if I can find a work around, I love the idea of this channel.

**Comment by sharkone** [comment]
I'm currently working on the streamer written in Go ([scrapmagnet](github.com/sharkone/scrapmagnet)). This will statically compiled for all supported OSes including Linux/x64. Bear with me :)

**Comment by sharkone** [comment]
Should be ok with 9f7d232574075e07cf60ec0a157a3dbf469c56c8.

https://forums.plex.tv/index.php/topic/102253-rel-bittorrent-channel/?p=874160

Please report back :)

**Comment by sharkone** [comment]
All good here? :)

**Comment by sgu222e** [comment]
Updated using the UAS and was able to get video playback
Fedora 21 Server x64 using Chrome to view.

**Comment by sharkone** [comment]
Oh yeah!
