### ISSUE TITLE
where do downloaded files go?

### ISSUE THREAD

**Issue by reharik** [sharkone/BitTorrent.bundle#36]
Hey, this isn't really a bug or anything but I can't figure out where the app stores downloaded files/movies.  I have the feature turned on and I've dug around the file system a bit but don't see any movie files.
If you could help that would be great.
Thanks,
r

**Comment by sharkone** [comment]
If you didn't change the default values, then you're downloaded files will be found somewher under: %LOCALAPPDATA%\Plex Media Server

Can't check exactly right now.
