### ISSUE TITLE
Content Unavailable

### ISSUE THREAD

**Issue by zysysgy** [sharkone/BitTorrent.bundle#38]
When trying to load content i keep getting an error. It reads: "Content Unavailable - An error occurred while trying to load this content, make sure the server is running". Most of the other unsupported applications seem to work fine, i've tried resetting plex and the roku to no available. The issue seems to plague other users on the plex addon forum. [url]https://forums.plex.tv/index.php/topic/102253-rel-bittorrent-channel/[/url]. 

Running Linux Mint 17 (Ubuntu 14.04) 64bit. 

Thank you for maintaining this awesome app!

**Comment by sharkone** [comment]
Dup #21
