### ISSUE TITLE
PMS latest, Windows 7 32Bit , only Anime bittorent channel working 

### ISSUE THREAD

**Issue by Kushmaro** [sharkone/BitTorrent.bundle#44]
only the anime channel is working for some reason.
If I choose Tv / Movies , and then any of the 'popular / new /genere' I get - "The channel is not responding"

Can't seem to load the torrents ? 
configuration seems ok, removed pirate bay since its dead...

no firewall , etc.
any suggestions?

**Comment by sharkone** [comment]
Everything should be fine now.
