### ISSUE TITLE
KickassTorrents Service ends up playing the trailer off the KA page rather than the torrent

### ISSUE THREAD

**Issue by jpunwin** [sharkone/BitTorrent.bundle#45]
Hello,

I have tried to get this working, I noticed that the service is raising the KA url for the movie as a service url which then plays the first vid it can find off that page (generally the trailer).

It looks as though it is not even using the media object.

**Comment by jpunwin** [comment]
I tested the same app on MacOS seems to work, so I am going to go through the logs now to try and diagnose the issue. Maybe something to do with the service mapping.

**Comment by sharkone** [comment]
Not really relevant anymore since we're now using the Scrapyard server.
