### ISSUE TITLE
Version 0.7.0 - videos found by Scrapyard service, but will not play

### ISSUE THREAD

**Issue by aitese** [sharkone/BitTorrent.bundle#47]
Any attempt to play a video from the browser (Chrome) results in being taken to a URL starting with http://scrapyard.en-mousse.org/.

Items are found and cover art shown. TV shows resolve with multiple search results as expected but none of the videos will play.

Will not play in browser, Plex Home Theatre, Chromecast or Plex for Android.

![plex_bt_01](https://cloud.githubusercontent.com/assets/558998/6011646/4b2d47d2-ab36-11e4-84aa-d9924f7a44d2.JPG)
![plex_bt_02](https://cloud.githubusercontent.com/assets/558998/6011648/50eb3670-ab36-11e4-818a-e17ebd86792f.JPG)
![plex_bt_03](https://cloud.githubusercontent.com/assets/558998/6011672/96771dbc-ab36-11e4-9179-8b66c7f2690f.JPG)

URL shows following output:

{
  "art": "https://walter.trakt.us/images/episodes/000/961/880/screenshots/original/e81373029a.jpg?1420574254", 
  "episode_index": 1, 
  "first_aired": "2014-09-22T17:00:00.000-07:00", 
  "magnets": [
    {
      "link": "magnet:?xt=urn:btih:4FDFFD286EF43393CFB21E9E627804F61F77AE4F&dn=gotham+s01e01+hdtv+x264+lol+ettv&tr=udp%3A%2F%2Fcastradio.net%3A6969%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337", 
      "peers": 2328, 
      "seeds": 2235, 
      "title": "Gotham S01E01 HDTV x264-LOL[ettv]"
    }, 
    {
      "link": "magnet:?xt=urn:btih:45262B37BE098C3011E90A1E3E2E5C04F1775157&dn=Gotham.S01E01.HDTV.x264-LOL&tr=udp://tracker.openbittorrent.com:80&tr=udp://open.demonii.com:80&tr=udp://tracker.coppersurfer.tk:80&tr=udp://tracker.leechers-paradise.org:6969&tr=udp://exodus.desync.com:6969", 
      "peers": 15, 
      "seeds": 419, 
      "title": "Gotham.S01E01.HDTV.x264-LOL"
    }, 
    {
      "link": "magnet:?xt=urn:btih:E3A79E33BB47741D83DEA392F71716720188D393&dn=gotham+s01e01+1080p+hdtv+subtitles&tr=udp%3A%2F%2Fopen.demonii.com%3A1337%2Fannounce", 
      "peers": 346, 
      "seeds": 276, 
      "title": "Gotham S01E01 1080p HDTV + Subtitles"
    }, 
    {
      "link": "magnet:?xt=urn:btih:90DFB20646CB7B220FE07D4D85CB0A7351C188C1&dn=gotham+s01e01+hdtv+x264+lol&tr=udp%3A%2F%2F12.rarbg.me%3A80%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337", 
      "peers": 272, 
      "seeds": 243, 
      "title": "Gotham S01E01 HDTV x264-LOL"
    }, 
    {
      "link": "magnet:?xt=urn:btih:FF176C10DFFEA348E2A31BB18016756A11BFEEF5&dn=Gotham.S01E01.720p.HDTV.X264-DIMENSION&tr=udp://tracker.openbittorrent.com:80&tr=udp://open.demonii.com:80&tr=udp://tracker.coppersurfer.tk:80&tr=udp://tracker.leechers-paradise.org:6969&tr=udp://exodus.desync.com:6969", 
      "peers": 50, 
      "seeds": 192, 
      "title": "Gotham.S01E01.720p.HDTV.X264-DIMENSION"
    }, 
    {
      "link": "magnet:?xt=urn:btih:C090752BCFE64560B199939CF123B2195AAD04D8&dn=gotham+s01e01+720p+hdtv+x264+dimension&tr=udp%3A%2F%2F12.rarbg.me%3A80%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337", 
      "peers": 162, 
      "seeds": 160, 
      "title": "Gotham S01E01 720p HDTV X264-DIMENSION"
    }, 
    {
      "link": "magnet:?xt=urn:btih:AF09C8E2FACBEC0A8ECC53F06D794A18A466E1AE&dn=gotham+s01e01+hdtv+xvid+fum+ettv&tr=udp%3A%2F%2Fcastradio.net%3A6969%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337", 
      "peers": 112, 
      "seeds": 106, 
      "title": "Gotham S01E01 HDTV XviD-FUM[ettv]"
    }, 
    {
      "link": "magnet:?xt=urn:btih:CB8B56826107F982304D9FBD22B4FB6C0070C0C8&dn=gotham+s01e00+01+h264+eng+aac+softsub+ita+hdtvrip+series+premi%C3%A8re&tr=udp%3A%2F%2Fopen.demonii.com%3A1337%2Fannounce", 
      "peers": 91, 
      "seeds": 81, 
      "title": "Gotham S01e00-01, [H264 - Eng Aac - SoftSub Ita] HDTVrip Series premi\u00e8re"
    }, 
    {
      "link": "magnet:?xt=urn:btih:3F7E47F3503503B13E393455FE3573D70DACD9DF&dn=gotham+s01e01+hdtv+xvid+evo&tr=udp%3A%2F%2Fopen.demonii.com%3A1337%2Fannounce", 
      "peers": 106, 
      "seeds": 75, 
      "title": "Gotham S01E01 HDTV XviD-EVO"
    }, 
    {
      "link": "magnet:?xt=urn:btih:4E6CF616A1C3FDBADC11E7B2F02383A9E6641A68&dn=gotham+s01e01+fastsub+vostfr+hdtv+xvid+addiction&tr=udp%3A%2F%2Ftracker.secureboxes.net%3A80%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337", 
      "peers": 54, 
      "seeds": 52, 
      "title": "Gotham S01E01 FASTSUB VOSTFR HDTV XviD-ADDiCTiON"
    }, 
    {
      "link": "magnet:?xt=urn:btih:571A971EA53B8A621A53B64430F4A5098B76AE88&dn=gotham+s01e01+hdtv+x264+lol+vtv+mp4&tr=http%3A%2F%2Ftracker.trackerfix.com%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337", 
      "peers": 54, 
      "seeds": 49, 
      "title": "Gotham S01E01 HDTV x264-LOL [VTV] mp4"
    }, 
    {
      "link": "magnet:?xt=urn:btih:2E9912364ED25CA5721555C80AF701706EE1F7A7&dn=gotham+1x01+le+regole+di+gotham+web+dl+1080p+x264+ac3+ita+eng+5+1+sub+ita+eng+mkv+r0ttenbl00d&tr=udp%3A%2F%2Fopen.demonii.com%3A1337%2Fannounce", 
      "peers": 89, 
      "seeds": 47, 
      "title": "Gotham 1x01 - Le Regole Di Gotham [Web-dl 1080p X264 AC3 ITA-ENG 5.1 Sub Ita-Eng MKV] R0ttenbl00d"
    }, 
    {
      "link": "magnet:?xt=urn:btih:86DB0647A452FF6B5BF14F4159E6214F472E4F82&dn=gotham+s01e01+pilot+480p+hdtv+x264+msd&tr=udp%3A%2F%2Fopen.demonii.com%3A1337%2Fannounce", 
      "peers": 49, 
      "seeds": 45, 
      "title": "Gotham S01E01 Pilot 480p HDTV x264-mSD"
    }, 
    {
      "link": "magnet:?xt=urn:btih:FF5163370B93B8058B45DC8861CD7D160BF681C6&dn=gotham+s01e01+720p+hdtv+x264+dimension&tr=udp%3A%2F%2Fopen.demonii.com%3A1337%2Fannounce", 
      "peers": 141, 
      "seeds": 35, 
      "title": "Gotham S01E01 720p HDTV X264-DIMENSION"
    }, 
    {
      "link": "magnet:?xt=urn:btih:EE897C17919E93DD9903EDD3ECEDCE91C55D6393&dn=gotham+s01e01+hdtv+x264+chamee&tr=udp%3A%2F%2Fopen.demonii.com%3A1337%2Fannounce", 
      "peers": 33, 
      "seeds": 28, 
      "title": "Gotham S01E01 HDTV x264-ChameE"
    }, 
    {
      "link": "magnet:?xt=urn:btih:7ADA4962B02A30FE214A015CE8069EB278BC29D7&dn=gotham+s01e01+hdtv+nl+sub+bbt+pilot&tr=udp%3A%2F%2Fopen.demonii.com%3A1337%2Fannounce", 
      "peers": 27, 
      "seeds": 26, 
      "title": "Gotham S01E01 HDTV NL Sub - BBT ( Pilot )"
    }, 
    {
      "link": "magnet:?xt=urn:btih:38612CE254C30E00489873144FEC239B1C1374FD&dn=gotham+s01+e01+13+of+22+2014+15+web+dl+1080p+dual+audio+ru+en&tr=udp%3A%2F%2Fopen.demonii.com%3A1337%2Fannounce", 
      "peers": 83, 
      "seeds": 25, 
      "title": "Gotham [S01:E01-13 of 22] (2014-15) WEB-DL 1080p Dual Audio [Ru-En]"
    }, 
    {
      "link": "magnet:?xt=urn:btih:81053DB7F965DA9EF64C91F9FC489652C420CD6A&dn=gotham+s01e01+e05+720p+hdtv+nl+subs+dutchreleaseteam&tr=udp%3A%2F%2Fopen.demonii.com%3A1337%2Fannounce", 
      "peers": 28, 
      "seeds": 22, 
      "title": "Gotham S01E01-E05 720p HDTV NL Subs DutchReleaseTeam"
    }, 
    {
      "link": "magnet:?xt=urn:btih:644FE59CD70ECCCB921E5B18F6D0D621B5244F0C&dn=gotham+s01e01+e05+hdtv+nl+subs+dutchreleaseteam&tr=udp%3A%2F%2Fopen.demonii.com%3A1337%2Fannounce", 
      "peers": 24, 
      "seeds": 19, 
      "title": "Gotham S01E01-E05 HDTV NL Subs DutchReleaseTeam"
    }, 
    {
      "link": "magnet:?xt=urn:btih:C980ED227E03F35F6F98559C3E853FB28218A680&dn=gotham+s01e01+v+hevc+720p+h265+ita+eng+aac+softsub+ita+eng+webdlmux&tr=udp%3A%2F%2Fopen.demonii.com%3A1337%2Fannounce", 
      "peers": 21, 
      "seeds": 18, 
      "title": "Gotham S01e01 V. HEVC, [720p - H265 - Ita Eng Aac - SoftSub Ita Eng] WEBDLmux"
    }, 
    {
      "link": "magnet:?xt=urn:btih:DB484097A183B9791CD4A4B05DDD158838D071DD&dn=gotham+s01e01+pilot+web+dl+x264+aac&tr=udp%3A%2F%2F12.rarbg.me%3A80%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337", 
      "peers": 19, 
      "seeds": 17, 
      "title": "Gotham S01E01 Pilot WEB-DL x264 AAC"
    }, 
    {
      "link": "magnet:?xt=urn:btih:D8C94C476E7EC06FAC93576A86829F7ACAA5182E&dn=gotham+s01e01+720p+hdtv+aac+x264+psypher&tr=udp%3A%2F%2Fopen.demonii.com%3A1337%2Fannounce", 
      "peers": 16, 
      "seeds": 13, 
      "title": "Gotham S01E01 720p HDTV AAC x264-PSYPHER"
    }, 
    {
      "link": "magnet:?xt=urn:btih:8D02C6B21BCC0B4DB6DD06E1368A07E21F823611&dn=gotham+s01e01+nl+avi&tr=udp%3A%2F%2Fopen.demonii.com%3A1337%2Fannounce", 
      "peers": 14, 
      "seeds": 12, 
      "title": "Gotham S01E01 nl.avi"
    }, 
    {
      "link": "magnet:?xt=urn:btih:7D8C7646AB610B6C31CC5D5C70D2C1D77D150AE9&dn=gotham+s01e01+hdtv+x264+lol&tr=udp%3A%2F%2Fopen.demonii.com%3A1337%2Fannounce", 
      "peers": 11, 
      "seeds": 9, 
      "title": "Gotham S01E01 HDTV x264-LOL"
    }, 
    {
      "link": "magnet:?xt=urn:btih:4AB0D4C093ED572E98774B9740DD797F612D7A49&dn=gotham+s01e01+720p+5+1ch+web+dl+reenc+deejayahmed&tr=udp%3A%2F%2Fglotorrents.com%3A6969%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337", 
      "peers": 10, 
      "seeds": 8, 
      "title": "Gotham S01E01 720p 5.1Ch Web-DL ReEnc DeeJayAhmed"
    }, 
    {
      "link": "magnet:?xt=urn:btih:033F3131E211B98E74C100E112D344022C6C2AD0&dn=gotham+s01e01+720p+hdtv+x264+aac+ozlem&tr=udp%3A%2F%2Fopen.demonii.com%3A1337%2Fannounce", 
      "peers": 7, 
      "seeds": 7, 
      "title": "Gotham S01E01 720p HDTV x264 AAC - Ozlem"
    }, 
    {
      "link": "magnet:?xt=urn:btih:790B4AC16F6EBBEBD467D1C515902B7519915F2C&dn=gotham+s01e01+1080p+webrip+x264+xred&tr=udp%3A%2F%2Fopen.demonii.com%3A1337%2Fannounce", 
      "peers": 8, 
      "seeds": 7, 
      "title": "Gotham S01E01 1080p WEBRip x264-xRed"
    }
  ], 
  "overview": "Detective James Gordon performs his work in the dangerously corrupt city of Gotham, which consistently teeters between good and evil.", 
  "rating": 8.00334, 
  "season_index": 1, 
  "show_title": "Gotham", 
  "thumb": "https://walter.trakt.us/images/episodes/000/961/880/screenshots/original/e81373029a.jpg?1420574254", 
  "title": "Pilot"
}

**Comment by sharkone** [comment]
Check your About page. I'm pretty sure it will say the URLService is not running, meaning you have to restart your server.

**Comment by aitese** [comment]
1. Where is the "About page" you're referencing? I've searched Google for any reference to a Plex "about page" to no avail.

2. How would I go about checking the status of the URLService?

![screenshot 2015-02-03 08 51 02](https://cloud.githubusercontent.com/assets/558998/6017050/d625e6aa-ab81-11e4-838e-46ca70bb7ef8.png)

This is the only Plex about screen. There is no information about running services.

3. I do QA for a living and I've never seen someone so trigger happy about closing issues before anything even resembling a thorough investigation. You've not even asked for relevant logs

No matter. I have restarted my server, given ample time for any services to start and attempted the process again with the same results. 

This is the Plex Media Server log: http://pastebin.com/Vj0jz6Q1
This is the Bittorent plugin log: http://pastebin.com/Y9686hBK

The only references to a URLService are these lines:

2015-02-03 08:39:18,509 (4104) :  DEBUG (services:41) - Loading service code for BitTorrent (URLServiceRecord)
2015-02-03 08:39:18,618 (4104) :  DEBUG (services:41) - Loading service code for Fallback (URLServiceRecord)
2015-02-03 08:39:18,713 (4104) :  WARNING (objectkit:200) - Media part has no streams - attempting to synthesize
2015-02-03 08:39:18,713 (4104) :  DEBUG (services:615) - Found a service matching '

**Comment by sharkone** [comment]
Yeah sorry maybe I went too fast here :)

The About can be found on the main menu page of the plugin (next to Movies and TV Shows).


Also looking at your BitTorrent log I can see:
```2015-02-03 08:35:51,490 (30c4) :  CRITICAL (core:572) - Error loading shared code (most recent call last):

  File "C:\Users\Aitese\AppData\Local\Plex Media Server\Plug-ins\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\components\services.py", line 435, in _setup_shared_code_sandbox

    sandbox.execute(code)

  File "C:\Users\Aitese\AppData\Local\Plex Media Server\Plug-ins\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\code\sandbox.py", line 256, in execute

    exec(code) in self.environment

  File "<shared>", line 5, in <module>

  File "C:\Users\Aitese\AppData\Local\Plex Media Server\Plug-ins\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\code\sandbox.py", line 333, in __import__

    return mod.load_module(_name)

  File "C:\Users\Aitese\AppData\Local\Plex Media Server\Plug-ins\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\code\sandbox.py", line 44, in load_module

    module = RestrictedModule(name, path, sandbox)

  File "C:\Users\Aitese\AppData\Local\Plex Media Server\Plug-ins\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\code\loader.py", line 30, in __init__

    exec(code) in self.__dict__

  File "C:\Users\Aitese\AppData\Local\Plex Media Server\Plug-ins\BitTorrent.bundle\Contents\Services\Shared Code\kickasstorrents.pys", line 19, in <module>

    class KickassTorrentsProvider(common.TorrentProvider):

AttributeError: 'RestrictedModule' object has no attribute 'TorrentProvider' ```

Indicating that you probably updated the plugin by copying over the existing directory which ended up "merging" them, leaving unwanted files behind.

Deleting the directory completely, reinstalling and restarting the server should do the trick.

Adding a new proper update mechanism independent from UAS is close on my list.

Let me know how it goes and thanks for your report.

**Comment by aitese** [comment]
**Deleting the directory completely, reinstalling and restarting the server should do the trick.**

Excellent. As usual the QA caused the issue :)

It's working now and I must say, great work, you're a genius!

**Comment by sharkone** [comment]
Thank you for your kind words!
Glad everything worked out!

**Comment by robinklein** [comment]
Hi,
I'm having the same issue, when I want to play a file on the bittorent channel, a new window appears and bring me to a URL like: http://scrapyard.en-mousse.org/api/movie/inside-out-2015?magnet=magnet%3A%3Fxt%3Durn%3Abtih%3A4B3DCE31C713B02726F67E2EF49DE9FF965EC3B7%26dn%3Dinside%2Bout%2B2015%2B720p%2Bbrrip%2Bx264%2Byify%26tr%3Dudp%253A%252F%252Ftracker.publicbt.com%252Fannounce%26tr%3Dudp%253A%252F%252Fopen.demonii.com%253A1337

What are the steps to deleting the repository completely?
Thanks
