### ISSUE TITLE
Playback Failed: One or More Items Failed to Play with Plex Home Theater

### ISSUE THREAD

**Issue by dulguldur** [sharkone/BitTorrent.bundle#48]
Hello,

I have Plex server Version 0.9.11.4 (Web Version 2.3.15) running on Ubuntu server 14.04.1. I was able to play two movies on Plex web from a machine running os x, however I get a "playback failed: one or more items failed to play" error when trying to play with Plex Home Theater on a separate Windows 7 x64 machine. 

Any idea why this might be?

Thanks for any help, and the effort put into developing this neat software!

**Comment by sharkone** [comment]
Any chance you're using a VPN?

**Comment by dulguldur** [comment]
The VPN fix setting was checked before I updated Plex server. When I updated Plex server, it seems to work now. The temporary files are downloaded on the server correct?

**Comment by sharkone** [comment]
Yup, PMS handles everything.
Can I close this issue?

**Comment by dulguldur** [comment]
I believe so. Thanks so much, sharkone! You pwn!!

**Comment by sharkone** [comment]
You're welcome!
