### ISSUE TITLE
Use UPNP to configure the bittorrent port

### ISSUE THREAD

**Issue by mrsvan** [sharkone/BitTorrent.bundle#53]
UPNP support would make the use of the bundle much easier!

**Comment by sharkone** [comment]
It's actually already there and enabled by default!

**Comment by mrsvan** [comment]
I actually opened this TT because my torrents were always being paused, and I thought it was because they weren't getting any traffic from outside my network.

I mapped the bundle's bittorrent ports manually on my external router... and that seemed to imporve the situation a bit (torrents paused after a longer time). But in the end, the torrents paused anyway, even with the manually defined bittorrent ports.

I'll double check my config and close this issue if UPNP is working correctly, and open a different TT for the pausing torrents...

**Comment by sharkone** [comment]
What do you mean torrents are getting paused? Did you see that on the scrapmagnet page? Torrents are paused when no playback activity is detected. So you have to be playing in the client to keep the torrent alive (pausing the playback in the client should still prevent the torrent pause, but stopping the playback will end up by pausing the transfer).

**Comment by sharkone** [comment]
Any news @mrsvan ?

**Comment by mrsvan** [comment]
Hello Thomas,

I have not yet had the time to packet sniff my installation and confirm that UPNP is working. but it remains on my TODO list.

Regarding the "pausing" of streams, I am a bit confused: there is an option to keep files downloaded files, and I would think that when you want to keep downloaded files, they should be downloaded entirely - even if you are not viewing the film...  In addition, once a download is paused after stopping/pausing playback, it looks like a completely new download is triggered when you resume the playback,.. I guess the non-UPNP issues are better discussed in the forum, rather than in this ticket, so I will pick-up the discussion there.

I'll try and get you a decisive response regarding UPNP over the weekend...

**Comment by mrsvan** [comment]
Hello Thomas,

I double-checked the bittorrent.bundle settings and I found the UPNP option.

It was indeed enabled.

I checked my router's UPNP config, and the bittorrent ports were correctly assigned!

So everything looks OK with UPNP.

I'll be closing the TT.

**Comment by sharkone** [comment]
Thanks for the followup!
