### ISSUE TITLE
Can't play anything

### ISSUE THREAD

**Issue by matrixino** [sharkone/BitTorrent.bundle#55]
Logs: http://pastebin.com/L0Gi1xXZ

Sometimes I get the error with a 5secs countdown and sometimes just "unable to reproduce..."
Ports are all open, if i try to download via a torrent client i can get the same magnet at 1/1,5Mbps download speed.
Everything is ok in About.

**Comment by sharkone** [comment]
Have you tried not limiting the upload rate by any chance (putting back 0). 10 is pretty low.

**Comment by matrixino** [comment]
I'll try. However in normal torrent client i get 1,5-1,7 MB/s even with just 2kB in upload. Unfortunately our country doesn't give much upload rate to DSLs (only 512kbps) so i must keep it under 15kB.
