### ISSUE TITLE
I'm always getting an error when trying to play content

### ISSUE THREAD

**Issue by brunobasto** [sharkone/BitTorrent.bundle#57]
So, it's my first time trying to run this plugin and I find the idea awesome. BUT I still haven't been able to play anything yet. Here's what I get:

![Bitrorrent Error](http://ibin.co/233uwEx78BOh)

And here's the log file:

https://gist.github.com/brunobasto/1533f27ff806bf76b4fc

**Comment by sharkone** [comment]
Hi there,
looking at your log you seem to have an invalid installation. Reported version seems to be 0.8.2 which is pretty old.

Try deleting and reinstalling latest version (0.9.0).

**Comment by brunobasto** [comment]
Will try it right now. Thanks for awesome quick response.

**Comment by brunobasto** [comment]
Okay, same error and here's the new log: https://gist.github.com/brunobasto/62a0934f294ed27fe69a

**Comment by brunobasto** [comment]
And here's the system log: https://gist.github.com/brunobasto/e1f30677a880d416b1c2 @sharkone

**Comment by sharkone** [comment]
Ok so the error seems to be here
```
 os.chmod(get_exec_path(), stat.S_IRUSR | stat.S_IWUSR | stat.S_IXUSR | stat.S_IRGRP | stat.S_IXGRP | stat.S_IROTH | stat.S_IXOTH)
OSError: [Errno 1] Operation not permitted: '/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/BitTorrent.bundle/Contents/Bin/linux_amd64/scrapmagnet'
 ```

There seems to be a permission issue here. I guess the channel directories and files don't have the proper permissions.

Maybe [https://support.plex.tv/hc/en-us/articles/200288596](this) could help you

**Comment by brunobasto** [comment]
Thank you. Looks like permissions are correct now, but I'm still not able to play any content. Here are the log files:

System Log: https://gist.github.com/brunobasto/10e2170daa7a5b44f690

Bittorrent Log: https://gist.github.com/brunobasto/c5cafb7d2323ae5b3f78

**Comment by sharkone** [comment]
You just seem to have tried with a torrent with very few seeders.
Try with a trending movie.

You can always check the status of scrapmagnet (the downloader) by visiting http://your.server.ip:8042

**Comment by brunobasto** [comment]
I have just tried Game of Thrones with 540 Seeds.

![Bitrorrent Error](http://ibin.co/234KU7e4OkL3)

Mybe the player is timing out? Is there a config to increase the timeout time? Also, I can't see any progress bar/percentage. That would help a lot to have an idea of what's going on in terms of connection speed (if that's my case).

**Comment by sharkone** [comment]
Unfortunately it's impossible to display anything :(
You can use the URL I gave you check the status. Maybe you have a connectivity issue.
You can also try pressing play a couple of times, if you hit the Plex Web timeout, pressing play again should help.

**Comment by brunobasto** [comment]
Looking through the logs, It seems the service starts waiting for movie to be ready, but at some point it just gives up: ´´2015-05-26 12:13:14,280 (7f4f87fff700) :  INFO (ServiceCode:124) - Video is not ready yet, redirecting´´

It doesn't take too long for it to give up. I would say less than a minute.

**Comment by brunobasto** [comment]
The URL you gave me always give me an empty array ``[]``

**Comment by brunobasto** [comment]
Plex doesn't offer any kind of API to display notifications? That sucks

**Comment by sharkone** [comment]
This doesn't make sense. While waiting for the video to load, you should have info on the scrapmagnet page.

**Comment by brunobasto** [comment]
Yeah. That's what I thought would happen. But it doesn't display anything

**Comment by sharkone** [comment]
Try restarting your computer and your PMS.

**Comment by brunobasto** [comment]
Okay, restarting my computer (and PMS because PMS lives in my computer in my case). Did the trick. Thank you very much for your help! Hope this thread helps others going thru the same issue.

**Comment by sharkone** [comment]
Great news!
Thanks for your help debugging the issue!
