### ISSUE TITLE
Not working under OS X El Captain

### ISSUE THREAD

**Issue by Qballjos** [sharkone/BitTorrent.bundle#59]
the plugin doesn't seem to work under OS X El Captain public beta 15A243D

Here is a Plugin log from my server.

http://pastebin.com/JNN1U8ES

**Comment by rdkls** [comment]
Having the same issue, but just with Yosemite 10.10.5 (14F27)

Unfortunately can't see any obvious errors in logs
http://pastebin.com/GwVMF7Cx

Response from http://localhost:8042/
http://pastebin.com/v01YByE9

Have tried rebooting, uninstall / reinstall PMS + plugin

If I run dtruss on scrapmagnet process, the only interesting things I see are read/write the request to port 8042.

**Comment by sharkone** [comment]
It works fine me on El Capitan.
Do you still the issue?
