### ISSUE TITLE
Binary for linux_armv7

### ISSUE THREAD

**Issue by jamesotron** [sharkone/BitTorrent.bundle#63]
Hi there.

I'm running my Plex Media Server on a Raspberry Pi 2B (Quad-code 1GHz) and it works admirably. Any chance you could add an armv7 binary to your plugin so that I can install it? Thanks.

**Comment by cjwsam** [comment]
id deffo be keen for this 2 coz i run plex media server on odroid xu4 octa core 
SBC are the way forward 

PLEASE source code or add ARM support :)
