### ISSUE TITLE
Scrapyard server (scrapyard.en-mousse.org) unavailable?

### ISSUE THREAD

**Issue by nchauley** [sharkone/BitTorrent.bundle#64]
Howdy. Can't seem to connect to scrapyard server in the past week or so - is it up? All was well previously.
Channel version: 1.0.3
PMS ver: 0.9.14.6
OS X ver: 10.10.5 (Yosemite)

Tried uninstall/reinstall of PMS and Bittorrent channel.

**Comment by computersteve** [comment]
yeah same the channel is reporting its down... is there an alternative =(

**Comment by nchauley** [comment]
OK - As of about 6 PM MDT Sat 01/09, Scrapyard server is back online - yaaaay! it's been up and stable for several hours now. 

Many Thx to whoever brought the server back online...

**Comment by computersteve** [comment]
I wanna say the server for me is very unreliable... it keeps going on and offline =( I wish there was some way we could pick a different one or had alternatives to the current one..

**Comment by sharkone** [comment]
Hi guys!
Yeah recently Heroku changed its free server model to force downtime during the day. I will soon change to their paid plan (or maybe change hosting altogether) and this should fix the issues you guys are having. I will also rewrite the scrapyard server using node.js to improve performance as well. Just need some time to do it :)

**Comment by nchauley** [comment]
Thx Tom - if u go the paid server route, I'll be happy to contribute to cost and thx again for all that you do to support and enhance the SS-plex channel.

Cheers!

**Comment by computersteve** [comment]
Just wanted to say that since yesterday the server has been down for me =( I'm running OS X 10.11.3

**Comment by sharkone** [comment]
Can you try opening http://scrapyard.en-mousse.org/api/movies/trending in your browser and see if it works?

**Comment by computersteve** [comment]
yeah that works.. it opens a page with a bunch of txt with this at the beginning {
  "movies": [
    {

**Comment by sharkone** [comment]
It should be ok now. Closing.
