### ISSUE TITLE
1.0.6 Native search broken

### ISSUE THREAD

**Issue by nchauley** [sharkone/BitTorrent.bundle#66]
Hello. Just upgraded to 1.0.6 and noticed that a search icon was added. While this lists a cumbersome sequential list of the alphabet and it does work after you spell the search term and hit submit, it also broke the previous search function (at the top of each panel) that was working perfectly fine in 1.0.5. Thought I'd report it. Thx...

Bitorrent ver: 1.0.6
OS X 10.11.3 (El Capitan)
Plex ver: 0.9.15.2

**Comment by sharkone** [comment]
Good catch!
I suppose you mean using Plex Web?

**Comment by sharkone** [comment]
Fixed in 1.0.7.
