### ISSUE TITLE
Trackers

### ISSUE THREAD

**Issue by s-dm** [sharkone/BitTorrent.bundle#69]
Now RIIA is train to kill torrent/file sharing and has gotten most browsers to block trackers like KAT.cr, and that is killing off the ppl who create the torrents and they are moving to other trackers, so could you either add some new 0day trackers or make it possible for us to add custom trackers via settings?

**Comment by s-dm** [comment]
It seems like the whole thing is broken now, tested on 2 servers and I can't find any torrents on tv shows, only on movies.

**Comment by blackami** [comment]
scrapyard.en-mousse.org gives error s3.amazonaws.com/heroku_pages/error.html
s-dm - how did you find a different server? Are there more servers?

**Comment by s-dm** [comment]
I meant home servers, hehe. Installed flex and bit torrent bundle on 2 servers to test, but gives me same error every time.

**Comment by blackami** [comment]
here is the example of the error: http://scrapyard.en-mousse.org/api/show/the-100/season/3/episode/11

**Comment by s-dm** [comment]
I can't even open that one..

**Comment by blackami** [comment]
![capture1](https://cloud.githubusercontent.com/assets/5263581/14589265/d6bc7672-04ab-11e6-9142-b1041577e6d1.PNG)

**Comment by s-dm** [comment]
Pretty annoying, hope there will be a fix soon or better yet another method for doing the whole bit torrent streaming on plex

**Comment by sharkone** [comment]
Should be fixed by sharkone/scrapyard.js@3ace5f13608df3a38589b40c9fb42108130d62a2

**Comment by blackami** [comment]
Thanks sharkone. 
I guess with the new changes there are many cases where titles are not unique anymore and seems like that causes plex to fail... This is just my guess, i know very little about plex or your code, but i just see error saying "KeyError: 'title'"
