### ISSUE TITLE
Xbox One App Search option

### ISSUE THREAD

**Issue by Deaths-Asylum** [sharkone/BitTorrent.bundle#72]
can you add xbox one client to dumbkeyboard please.  the search option doesnt come up like it does for android and the web app. id be happy to test it for you? Everything else works great, thank you. i am running PMS Version 0.9.17.2 on windows 7 64bit  using bittorrent.bundle version 1.0.8 webtools version 
2.2

_EDIT_
i went into the "code" folder inside the plugin and edit dumbtools.py by adding 'Plex for Xbox One' after clients and the search came up and it does work. not quite how it does in other apps but the end result is the same also you wont have the Search.png show at least it didnt for me. maybe if a string is added to point to this.

**Comment by spaz926** [comment]
#73 fixes this.

Can be closed.
