### ISSUE TITLE
Kat torrent

### ISSUE THREAD

**Issue by s-dm** [sharkone/BitTorrent.bundle#76]
After FBI now have shut down KAT, what options are you working on? Will you update for a new tracker?

**Comment by Kaobabob** [comment]
Bumping this comment.

**Comment by keberwein** [comment]
Would it be possible to move to TPB's API? Found this [python lib](https://github.com/karan/TPB). Looks like it's failing build tests on Travis-CI, but might be able to glean some logic form the [tpb.py](https://github.com/karan/TPB/blob/master/tpb/tpb.py) file.

**Comment by spaz926** [comment]
This plugin now uses Popcorn API (Extratorrent, YTS for movies and EZTV for tv shows). @sharkone this can be closed
